package net.brdviii.flowers.datagen;


import net.brdviii.flowers.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        RegistryWrapper.Impl<Enchantment> impl = this.registryLookup.getWrapperOrThrow(RegistryKeys.ENCHANTMENT);


        addDrop(ModBlocks.AFRICAN_DAISY);
        addDrop(ModBlocks.ALBUCA_NAMAQUENSIS);
        addDrop(ModBlocks.AUSTRALIAN_CORNFLOWER);
        addDrop(ModBlocks.AUSTRALIAN_FLAME_PEA);
        addDrop(ModBlocks.BABY_BLUE_EYES);
        addDrop(ModBlocks.BABY_BLUE_EYES_SMALL);
        addDrop(ModBlocks.BACHELOR_BUTTON);
        addDrop(ModBlocks.BANEBERRY);
        addDrop(ModBlocks.BEACH_GRASS);
        addDrop(ModBlocks.BEACH_STRAWBERRY);
        addDrop(ModBlocks.BIRDS_EYE_GILIA);
        addDrop(ModBlocks.BLEEDING_HEART);
        addDrop(ModBlocks.BLUE_BACHELOR_BUTTON);
        addDrop(ModBlocks.BLUE_BELL_BACHELOR_BUTTON);
        addDrop(ModBlocks.BLUE_BELL_SWEET_PEAS);
        addDrop(ModBlocks.BLUE_EYED_GRASS);
        addDrop(ModBlocks.BLUE_TINSEL_LILY);
        addDrop(ModBlocks.BORAGE);
        addDrop(ModBlocks.BRIGHT_MAGENTA_SWEET_PEAS);
        addDrop(ModBlocks.BUCKWHEAT);
        addDrop(ModBlocks.BUCKWHEAT_RED);
        addDrop(ModBlocks.CACTUS);
        addDrop(ModBlocks.CALIFORNIA_POPPY);
        addDrop(ModBlocks.CALIFORNIA_SEA_THRIFT);
        addDrop(ModBlocks.CALLA_LILY);
        addDrop(ModBlocks.CAPE_ALOE);
        addDrop(ModBlocks.CHRYSANTHENUM);
        addDrop(ModBlocks.CINQUEFOIL);
        addDrop(ModBlocks.CLOUD_BLUE_CORYDALIS);
        addDrop(ModBlocks.CLOVER_LILY);
        addDrop(ModBlocks.COASTAL_LOTUS);
        addDrop(ModBlocks.COMMELINA);
        addDrop(ModBlocks.COMMON_PERIWINKLE);
        addDrop(ModBlocks.CORYDALIS);
        addDrop(ModBlocks.COSMOS);
        addDrop(ModBlocks.COSMOS_MIX);
        addDrop(ModBlocks.CRACKING_RUSSULA);
        addDrop(ModBlocks.CREEPING_THYME);
        addDrop(ModBlocks.CRIMSON_GLADIOLA);
        addDrop(ModBlocks.CRINOLINE_STINKHORN);
        addDrop(ModBlocks.CROCUS_MIX);
        addDrop(ModBlocks.CYAN_HYACINTH);
        addDrop(ModBlocks.DAHLIA);
        addDrop(ModBlocks.DARK_BLUE_BORAGE);
        addDrop(ModBlocks.DARK_BLUE_SWEET_PEAS);
        addDrop(ModBlocks.DARKOSTO_TRAPOSTO);
        addDrop(ModBlocks.DATURA);
        addDrop(ModBlocks.DAY_LILY);
        addDrop(ModBlocks.DESERT_PAINTBRUSH);
        addDrop(ModBlocks.DESERT_SAND_VERBENA);
        addDrop(ModBlocks.DESERT_STURT_PEA);
        addDrop(ModBlocks.DEVILS_CLAW);
        addDrop(ModBlocks.DEVILS_FINGERS);
        addDrop(ModBlocks.DRIED_SUNFLOWER);
        addDrop(ModBlocks.ECHINACEA);
        addDrop(ModBlocks.ENGELMANNS_HEDGEHOG_CACTUS);
        addDrop(ModBlocks.FLOWERING_CURRENT);
        addDrop(ModBlocks.FORGET_ME_NOT);
        addDrop(ModBlocks.FROGBIT);
        addDrop(ModBlocks.FUCHSIA);
        addDrop(ModBlocks.GLADIOLA);
        addDrop(ModBlocks.GLORIOSA_LILY);
        addDrop(ModBlocks.GOLDEN_BEAN);
        addDrop(ModBlocks.GRAPE_HYACINTH);
        addDrop(ModBlocks.HAWTHORNE);
        addDrop(ModBlocks.HIMALAYAN_BLUE_POPPY);
        addDrop(ModBlocks.INKY_CAP);
        addDrop(ModBlocks.IRIS);
        addDrop(ModBlocks.IRIS_FANCY);
        addDrop(ModBlocks.JEWEL_OF_THE_DESERT);
        addDrop(ModBlocks.LADY_SLIPPER_ORCHID);
        addDrop(ModBlocks.LANTANA);
        addDrop(ModBlocks.LARKSPUR);
        addDrop(ModBlocks.LAVENDER_LARKSPUR);
        addDrop(ModBlocks.LEWISIA);
        addDrop(ModBlocks.LIGHT_BLUE_FORGET_ME_NOT);
        addDrop(ModBlocks.LIGHT_BLUE_LOBELIA);
        addDrop(ModBlocks.LIGHT_PINK_GERANIUM);
        addDrop(ModBlocks.LIGHT_PINK_LARKSPUR);
        addDrop(ModBlocks.MAGENTA_CLOVER);
        addDrop(ModBlocks.MAGENTA_LARKSPUR);
        addDrop(ModBlocks.MAGENTA_ORCHID);
        addDrop(ModBlocks.MAGENTA_SWEET_PEAS);
        addDrop(ModBlocks.MAGENTA_ZINNIA);
        addDrop(ModBlocks.MANZANITA_BUSH);
        addDrop(ModBlocks.MAROON_MALLOW);
        addDrop(ModBlocks.MEDIUM_BLUE_LOBELIA);
        addDrop(ModBlocks.MENDOCINO_POPPY);
        addDrop(ModBlocks.MEXICAN_SAGE);
        addDrop(ModBlocks.MIXED_PINK_SWEET_PEAS);
        addDrop(ModBlocks.MIXED_ZINNIA);
        addDrop(ModBlocks.MOJAVE_INDIGO_BUSH);
        addDrop(ModBlocks.MORNING_GLORY);
        addDrop(ModBlocks.NARCISSUS);
        addDrop(ModBlocks.NASTURTIUM);
        addDrop(ModBlocks.NASTURTIUM_PINK);
        addDrop(ModBlocks.NOTCH_LEAF_SCORPION_WEED);
        addDrop(ModBlocks.OCOTILLO);
        addDrop(ModBlocks.ORANGE_AUSTRALIAN_FLAME_PEA);
        addDrop(ModBlocks.ORANGE_COSMOS);
        addDrop(ModBlocks.ORANGE_DAY_LILY);
        addDrop(ModBlocks.ORANGE_FREESIA);
        addDrop(ModBlocks.ORANGE_GLADIOLA);
        addDrop(ModBlocks.ORANGE_LUPIN);
        addDrop(ModBlocks.ORNAMENTAL_CHERRY);
        addDrop(ModBlocks.OWLS_CLOVER);
        addDrop(ModBlocks.PANSY);
        addDrop(ModBlocks.PANSY_PURPLE);
        addDrop(ModBlocks.PARADOX_SUNFLOWER);
        addDrop(ModBlocks.PARODIA_MURICATA);
        addDrop(ModBlocks.PARROT_FLOWER);
        addDrop(ModBlocks.PEACH_GLADIOLA);
        addDrop(ModBlocks.PEPPERMINT);
        addDrop(ModBlocks.PERIWINKLE);
        addDrop(ModBlocks.PINK_CLOVER);
        addDrop(ModBlocks.PINK_DESERT_SAND_VERBENA);
        addDrop(ModBlocks.PINK_GERANIUM);
        addDrop(ModBlocks.PINK_LARKSPUR);
        addDrop(ModBlocks.PINK_PETTICOAT);
        addDrop(ModBlocks.PITCHER_PLANT);
        addDrop(ModBlocks.PURPLE_AFRICAN_DAISY);
        addDrop(ModBlocks.PURPLE_CALLA_LILY);
        addDrop(ModBlocks.PURPLE_CROCUS);
        addDrop(ModBlocks.PURPLE_FLAG);
        addDrop(ModBlocks.PURPLE_LARKSPUR);
        addDrop(ModBlocks.PURPLE_LUPIN);
        addDrop(ModBlocks.PURPLE_MAGENTA_SALVIA);
        addDrop(ModBlocks.PURPLE_SWEET_PEAS);
        addDrop(ModBlocks.QUINCE);
        addDrop(ModBlocks.RED_CLOVER);
        addDrop(ModBlocks.RED_FREESIA);
        addDrop(ModBlocks.RED_GERANIUM);
        addDrop(ModBlocks.RED_POPPY);
        addDrop(ModBlocks.RED_SUNFLOWER);
        addDrop(ModBlocks.ROCK_ROSE);
        addDrop(ModBlocks.ROYAL_BLUE_LOBELIA);
        addDrop(ModBlocks.SALVIA);
        addDrop(ModBlocks.SILVER_CARPET);
        addDrop(ModBlocks.SKYSCRAPER_SUNFLOWER);
        addDrop(ModBlocks.SNAPDRAGON_PINK);
        addDrop(ModBlocks.SNAPDRAGON_WHITE);
        addDrop(ModBlocks.SPROUT);
        addDrop(ModBlocks.STACKED_MORNING_GLORY);
        addDrop(ModBlocks.STACKED_NASTURTIUM);
        addDrop(ModBlocks.STACKED_NASTURTIUM_PINK);
        addDrop(ModBlocks.STICKY_MONKEY);
        addDrop(ModBlocks.STRIPED_ZINNIA);
        addDrop(ModBlocks.SUNDANCE_KID);
        addDrop(ModBlocks.SUNNY_ZINNIA);
        addDrop(ModBlocks.TALL_CACTUS);
        addDrop(ModBlocks.TALL_CALLA_LILY);
        addDrop(ModBlocks.TALL_COSMOS);
        addDrop(ModBlocks.TALL_LUPIN);
        addDrop(ModBlocks.TALL_ORANGE_COSMOS);
        addDrop(ModBlocks.TEDDY_BEAR_SUNFLOWER);
        addDrop(ModBlocks.TUMBLE_WEED);
        addDrop(ModBlocks.VENUS_FLY_TRAP);
        addDrop(ModBlocks.VIOLET);
        addDrop(ModBlocks.VIOLET_WEBCAP);
        addDrop(ModBlocks.VIRGINIA_COWSLIP);
        addDrop(ModBlocks.WATER_LILY_SMALL);
        addDrop(ModBlocks.WHITE_DAFFODIL);
        addDrop(ModBlocks.WHITE_LARKSPUR);
        addDrop(ModBlocks.WHITE_TINSEL);
        addDrop(ModBlocks.WOLFS_BANE);
        addDrop(ModBlocks.WOOLY_THYME);
        addDrop(ModBlocks.YELLOW_COSMOS);
        addDrop(ModBlocks.YELLOW_CROCUS);
        addDrop(ModBlocks.YELLOW_DAFFODIL);
        addDrop(ModBlocks.YELLOW_FREESIA);
        addDrop(ModBlocks.YELLOW_LUPIN);
        addDrop(ModBlocks.YELLOW_PATCHES);
        addDrop(ModBlocks.YELLOW_STARTHISTLE);
        addDrop(ModBlocks.YUCCA_FLOWER);

        addDrop(ModBlocks.JOY_LARGE_LILY);
        addDrop(ModBlocks.JOY_LIGHT_LILY);
        addDrop(ModBlocks.LAVANDER_LARGE_LILY);
        addDrop(ModBlocks.LAVANDER_LIGHT_LILY);
        addDrop(ModBlocks.PURPLE_LARGE_LILY);
        addDrop(ModBlocks.PURPLE_LIGHT_LILY);
        addDrop(ModBlocks.SUNFIRE_LARGE_LILY);
        addDrop(ModBlocks.SUNFIRE_LIGHT_LILY);

        addDrop(ModBlocks.WISTERIA_LAVANDER);
        addDrop(ModBlocks.WISTERIA_PURPLE);
        addDrop(ModBlocks.WISTERIA_WHITE);

        addDrop(ModBlocks.WISTERIA_LAVANDER_PLANT,ModBlocks.WISTERIA_LAVANDER);
        addDrop(ModBlocks.WISTERIA_PURPLE_PLANT,ModBlocks.WISTERIA_PURPLE);
        addDrop(ModBlocks.WISTERIA_WHITE_PLANT,ModBlocks.WISTERIA_WHITE);
    }
}
