package net.brdviii.flowers.datagen;

import net.brdviii.flowers.block.ModBlocks;
import net.brdviii.flowers.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLangProvider extends FabricLanguageProvider {
    public ModLangProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(ModBlocks.AFRICAN_DAISY,"African Daisy");
        translationBuilder.add(ModBlocks.ALBUCA_NAMAQUENSIS,"Albuca Namaquensis");
        translationBuilder.add(ModBlocks.AUSTRALIAN_CORNFLOWER,"Australian Cornflower");
        translationBuilder.add(ModBlocks.AUSTRALIAN_FLAME_PEA,"Australian Flame Pea");
        translationBuilder.add(ModBlocks.BABY_BLUE_EYES,"Baby Blue Eyes");
        translationBuilder.add(ModBlocks.BABY_BLUE_EYES_SMALL,"Baby Blue Eyes Small");
        translationBuilder.add(ModBlocks.BACHELOR_BUTTON,"Bachelor Button");
        translationBuilder.add(ModBlocks.BANEBERRY,"Baneberry");
        translationBuilder.add(ModBlocks.BEACH_GRASS,"Beach Grass");
        translationBuilder.add(ModBlocks.BEACH_STRAWBERRY,"Beach Strawberry");
        translationBuilder.add(ModBlocks.BIRDS_EYE_GILIA,"Birds Eye Gilia");
        translationBuilder.add(ModBlocks.BLEEDING_HEART,"Bleeding heart");
        translationBuilder.add(ModBlocks.BLUE_BACHELOR_BUTTON,"Blue Bachelor Button");
        translationBuilder.add(ModBlocks.BLUE_BELL_BACHELOR_BUTTON,"Blue Bell Bachelor Button");
        translationBuilder.add(ModBlocks.BLUE_BELL_SWEET_PEAS,"Blue Bell Sweet Peas");
        translationBuilder.add(ModBlocks.BLUE_EYED_GRASS,"Blue Eyes Grass");
        translationBuilder.add(ModBlocks.BLUE_TINSEL_LILY,"Blue Tinsel Lily");
        translationBuilder.add(ModBlocks.BORAGE,"Borage");
        translationBuilder.add(ModBlocks.BRIGHT_MAGENTA_SWEET_PEAS,"Bright Magenta Peas");
        translationBuilder.add(ModBlocks.BUCKWHEAT,"Buckwheat");
        translationBuilder.add(ModBlocks.BUCKWHEAT_RED,"Red Buckwheat");
        translationBuilder.add(ModBlocks.CACTUS,"Cactus");
        translationBuilder.add(ModBlocks.CALIFORNIA_POPPY,"California Poppy");
        translationBuilder.add(ModBlocks.CALIFORNIA_SEA_THRIFT,"California Sea Thrift");
        translationBuilder.add(ModBlocks.CALLA_LILY,"Calla Lily");
        translationBuilder.add(ModBlocks.CAPE_ALOE,"Cape Aloe");
        translationBuilder.add(ModBlocks.CHRYSANTHENUM,"Chrysanthenum");
        translationBuilder.add(ModBlocks.CINQUEFOIL,"Cinquefoil");
        translationBuilder.add(ModBlocks.CLOUD_BLUE_CORYDALIS,"Cloud Blue Corydalis");
        translationBuilder.add(ModBlocks.CLOVER_LILY,"Clover Lily");
        translationBuilder.add(ModBlocks.COASTAL_LOTUS,"Coastal Lotus");
        translationBuilder.add(ModBlocks.COMMELINA,"Commelina");
        translationBuilder.add(ModBlocks.COMMON_PERIWINKLE,"Common Periwinkle");
        translationBuilder.add(ModBlocks.COSMOS,"Cosmos");
        translationBuilder.add(ModBlocks.COSMOS_MIX,"Cosmos Mix");
        translationBuilder.add(ModBlocks.CRACKING_RUSSULA,"Cracking Russula");
        translationBuilder.add(ModBlocks.CREEPING_THYME,"Creeping Thyme");
        translationBuilder.add(ModBlocks.CRIMSON_GLADIOLA,"Crimson Gladiola");
        translationBuilder.add(ModBlocks.CRINOLINE_STINKHORN,"Crinoline Stinkhorn");
        translationBuilder.add(ModBlocks.CROCUS_MIX,"Crocus Mix");
        translationBuilder.add(ModBlocks.CYAN_HYACINTH,"Cyan Hyacinth");
        translationBuilder.add(ModBlocks.DAHLIA,"Dahlia");
        translationBuilder.add(ModBlocks.DARK_BLUE_BORAGE,"Dark Blue Borage");
        translationBuilder.add(ModBlocks.DARK_BLUE_SWEET_PEAS,"Dark Blue Sweet Peas");
        translationBuilder.add(ModBlocks.DARKOSTO_TRAPOSTO,"Darkosto Traposto");
        translationBuilder.add(ModBlocks.DATURA,"Datura");
        translationBuilder.add(ModBlocks.DAY_LILY,"Day Lily");
        translationBuilder.add(ModBlocks.DESERT_PAINTBRUSH,"Desert Paintbrush");
        translationBuilder.add(ModBlocks.DESERT_SAND_VERBENA,"Desert Sand Verbena");
        translationBuilder.add(ModBlocks.DESERT_STURT_PEA,"Desert Sturt Pea");
        translationBuilder.add(ModBlocks.DEVILS_CLAW,"Devils Claw");
        translationBuilder.add(ModBlocks.DEVILS_FINGERS,"Devils Fingers");
        translationBuilder.add(ModBlocks.DRIED_SUNFLOWER,"Dried Sunflower");
        translationBuilder.add(ModBlocks.ECHINACEA,"Echinacea");
        translationBuilder.add(ModBlocks.ENGELMANNS_HEDGEHOG_CACTUS,"Engelmanns Hedgehog Cactus");
        translationBuilder.add(ModBlocks.FLOWERING_CURRENT,"Flowering Current");
        translationBuilder.add(ModBlocks.FORGET_ME_NOT,"Forget Me Not");
        translationBuilder.add(ModBlocks.FROGBIT,"Frogbit");
        translationBuilder.add(ModBlocks.FUCHSIA,"Fuchsia");
        translationBuilder.add(ModBlocks.GLADIOLA,"Gladiola");
        translationBuilder.add(ModBlocks.GLORIOSA_LILY,"Gloriosa Lily");
        translationBuilder.add(ModBlocks.GOLDEN_BEAN,"Golden Bean");
        translationBuilder.add(ModBlocks.GRAPE_HYACINTH,"Grape Hyacinth");
        translationBuilder.add(ModBlocks.HAWTHORNE,"Hawthorne");
        translationBuilder.add(ModBlocks.HIMALAYAN_BLUE_POPPY,"Himalayan Blue Poppy");
        translationBuilder.add(ModBlocks.INKY_CAP,"Inky Cap");
        translationBuilder.add(ModBlocks.IRIS,"Iris");
        translationBuilder.add(ModBlocks.IRIS_FANCY,"Iris Fancy");
        translationBuilder.add(ModBlocks.JEWEL_OF_THE_DESERT,"Jewel Of The Desert");
        translationBuilder.add(ModBlocks.LADY_SLIPPER_ORCHID,"Lady Slipper Orchid");
        translationBuilder.add(ModBlocks.LANTANA,"Lantana");
        translationBuilder.add(ModBlocks.LARKSPUR,"Larkspur");
        translationBuilder.add(ModBlocks.LAVENDER_LARKSPUR,"Lavender Larkspur");
        translationBuilder.add(ModBlocks.LEWISIA,"Lewisia");
        translationBuilder.add(ModBlocks.LIGHT_BLUE_FORGET_ME_NOT,"Light Blue Forget Me Not");
        translationBuilder.add(ModBlocks.LIGHT_BLUE_LOBELIA,"Light Blue Lobelia");
        translationBuilder.add(ModBlocks.LIGHT_PINK_GERANIUM,"Light Ping Geranium");
        translationBuilder.add(ModBlocks.LIGHT_PINK_LARKSPUR,"Light Pink Larkspur");
        translationBuilder.add(ModBlocks.MAGENTA_CLOVER,"Magenta Clover");
        translationBuilder.add(ModBlocks.MAGENTA_LARKSPUR,"Magenta Larkspur");
        translationBuilder.add(ModBlocks.MAGENTA_ORCHID,"Magenta Orchid");
        translationBuilder.add(ModBlocks.MAGENTA_SWEET_PEAS,"Magenta Sweet Peas");
        translationBuilder.add(ModBlocks.MAGENTA_ZINNIA,"Magenta Zinnia");
        translationBuilder.add(ModBlocks.MANZANITA_BUSH,"Manzanita Bush");
        translationBuilder.add(ModBlocks.MAROON_MALLOW,"Maroon Mallow");
        translationBuilder.add(ModBlocks.MEDIUM_BLUE_LOBELIA,"Medium Blue Lobelia");
        translationBuilder.add(ModBlocks.MENDOCINO_POPPY,"Mendocino Poppy");
        translationBuilder.add(ModBlocks.MEXICAN_SAGE,"Mexica Sage");
        translationBuilder.add(ModBlocks.MIXED_PINK_SWEET_PEAS,"Mixed Pink Sweet Peas");
        translationBuilder.add(ModBlocks.MIXED_ZINNIA,"Mixed Zinnia");
        translationBuilder.add(ModBlocks.MOJAVE_INDIGO_BUSH,"Mojave Indigo Bush");
        translationBuilder.add(ModBlocks.MORNING_GLORY,"Morning Glory");
        translationBuilder.add(ModBlocks.NARCISSUS,"Narcissus");
        translationBuilder.add(ModBlocks.NASTURTIUM,"Nasturtium");
        translationBuilder.add(ModBlocks.NASTURTIUM_PINK,"Pink Nasturtium");
        translationBuilder.add(ModBlocks.NOTCH_LEAF_SCORPION_WEED,"Notch Leaf Scorpion Weed");
        translationBuilder.add(ModBlocks.OCOTILLO,"Ocotillo");
        translationBuilder.add(ModBlocks.ORANGE_AUSTRALIAN_FLAME_PEA,"Orange Australian Flame Pea");
        translationBuilder.add(ModBlocks.ORANGE_COSMOS,"Orange Cosmos");
        translationBuilder.add(ModBlocks.ORANGE_DAY_LILY,"Orange Day Lily");
        translationBuilder.add(ModBlocks.ORANGE_FREESIA,"Orange Freesia");
        translationBuilder.add(ModBlocks.ORANGE_GLADIOLA,"Orange Gladiola");
        translationBuilder.add(ModBlocks.ORANGE_LUPIN,"Orange Lupin");
        translationBuilder.add(ModBlocks.ORNAMENTAL_CHERRY,"Ornamental Cherry");
        translationBuilder.add(ModBlocks.OWLS_CLOVER,"Owls Clover");
        translationBuilder.add(ModBlocks.PANSY,"Pansy");
        translationBuilder.add(ModBlocks.PANSY_PURPLE,"Purple Pansy");
        translationBuilder.add(ModBlocks.PARADOX_SUNFLOWER,"Paradox Sunflower");
        translationBuilder.add(ModBlocks.PARODIA_MURICATA,"Parodia Muricata");
        translationBuilder.add(ModBlocks.PARROT_FLOWER,"Parrot Flower");
        translationBuilder.add(ModBlocks.PEACH_GLADIOLA,"Peach Gladiola");
        translationBuilder.add(ModBlocks.PEPPERMINT,"Peppermint");
        translationBuilder.add(ModBlocks.PERIWINKLE,"Periwinkle");
        translationBuilder.add(ModBlocks.PINK_CLOVER,"Pink Clover");
        translationBuilder.add(ModBlocks.PINK_DESERT_SAND_VERBENA,"Pink Desert Sand Verbena");
        translationBuilder.add(ModBlocks.PINK_GERANIUM,"Pink Geranium");
        translationBuilder.add(ModBlocks.PINK_LARKSPUR,"Pink Larkspur");
        translationBuilder.add(ModBlocks.PINK_PETTICOAT,"Pink Petticoat");
        translationBuilder.add(ModBlocks.PITCHER_PLANT,"Pitcher Plant");
        translationBuilder.add(ModBlocks.PURPLE_AFRICAN_DAISY,"Purple African Daisy");
        translationBuilder.add(ModBlocks.PURPLE_CALLA_LILY,"Purple Calla Lily");
        translationBuilder.add(ModBlocks.PURPLE_CROCUS,"Purple Crocus");
        translationBuilder.add(ModBlocks.PURPLE_FLAG,"Purple Flag");
        translationBuilder.add(ModBlocks.PURPLE_LARKSPUR,"Purple Larkspur");
        translationBuilder.add(ModBlocks.PURPLE_LUPIN,"Purple Lupin");
        translationBuilder.add(ModBlocks.PURPLE_MAGENTA_SALVIA,"Purple Magenta Salvia");
        translationBuilder.add(ModBlocks.PURPLE_SWEET_PEAS,"Purple Sweet Peas");
        translationBuilder.add(ModBlocks.QUINCE,"Quince");
        translationBuilder.add(ModBlocks.RED_CLOVER,"Red Clover");
        translationBuilder.add(ModBlocks.RED_FREESIA,"Red Freesia");
        translationBuilder.add(ModBlocks.RED_GERANIUM,"Red Geranium");
        translationBuilder.add(ModBlocks.RED_POPPY,"Red Poppy");
        translationBuilder.add(ModBlocks.RED_SUNFLOWER,"Red Sunflower");
        translationBuilder.add(ModBlocks.ROCK_ROSE,"Rock Rose");
        translationBuilder.add(ModBlocks.ROYAL_BLUE_LOBELIA,"Royal Blue Lobelia");
        translationBuilder.add(ModBlocks.SALVIA,"Salvia");
        translationBuilder.add(ModBlocks.SILVER_CARPET,"Silver Carpet");
        translationBuilder.add(ModBlocks.SKYSCRAPER_SUNFLOWER,"Skyscraper Sunflower");
        translationBuilder.add(ModBlocks.SNAPDRAGON_PINK,"Pink Snapdragon");
        translationBuilder.add(ModBlocks.SNAPDRAGON_WHITE,"White Snapdragon");
        translationBuilder.add(ModBlocks.SPROUT,"Sprout");
        translationBuilder.add(ModBlocks.STACKED_MORNING_GLORY,"Staked Morning Glory");
        translationBuilder.add(ModBlocks.STACKED_NASTURTIUM,"Staked Nasturtium");
        translationBuilder.add(ModBlocks.STACKED_NASTURTIUM_PINK,"Staked Pink Nasturtium");
        translationBuilder.add(ModBlocks.STICKY_MONKEY,"Sticky Monkey");
        translationBuilder.add(ModBlocks.STRIPED_ZINNIA,"Striped Zinnia");
        translationBuilder.add(ModBlocks.SUNDANCE_KID,"Sundance Kid");
        translationBuilder.add(ModBlocks.SUNNY_ZINNIA,"Sunny Zinnia");
        translationBuilder.add(ModBlocks.TALL_CACTUS,"Tall Cactus");
        translationBuilder.add(ModBlocks.TALL_CALLA_LILY,"Tall Calla Lily");
        translationBuilder.add(ModBlocks.TALL_COSMOS,"Tall Cosmos");
        translationBuilder.add(ModBlocks.TALL_LUPIN,"tall Lupin");
        translationBuilder.add(ModBlocks.TALL_ORANGE_COSMOS,"Tall Orange Cosmos");
        translationBuilder.add(ModBlocks.TEDDY_BEAR_SUNFLOWER,"Teddy Bear Sunflower");
        translationBuilder.add(ModBlocks.TUMBLE_WEED,"Tumble Weed");
        translationBuilder.add(ModBlocks.VENUS_FLY_TRAP,"Venus Fly Trap");
        translationBuilder.add(ModBlocks.VIOLET,"Violet");
        translationBuilder.add(ModBlocks.VIOLET_WEBCAP,"Violet Webcap");
        translationBuilder.add(ModBlocks.VIRGINIA_COWSLIP,"Virginia Cowslip");
        translationBuilder.add(ModBlocks.WATER_LILY_SMALL,"Small Lily");
        translationBuilder.add(ModBlocks.WHITE_DAFFODIL,"White Daffodil");
        translationBuilder.add(ModBlocks.WHITE_LARKSPUR,"White Larkspur");
        translationBuilder.add(ModBlocks.WHITE_TINSEL,"White Tinsel");
        translationBuilder.add(ModBlocks.WOLFS_BANE,"Wolfs Bane");
        translationBuilder.add(ModBlocks.WOOLY_THYME,"Wooly Thyme");
        translationBuilder.add(ModBlocks.YELLOW_COSMOS,"Yellow Cosmos");
        translationBuilder.add(ModBlocks.YELLOW_CROCUS,"Yellow Crocus");
        translationBuilder.add(ModBlocks.YELLOW_DAFFODIL,"Yellow Daffodil");
        translationBuilder.add(ModBlocks.YELLOW_FREESIA,"Yellow Freesia");
        translationBuilder.add(ModBlocks.YELLOW_LUPIN,"Yellow Lupin");
        translationBuilder.add(ModBlocks.YELLOW_PATCHES,"Yellow Patches");
        translationBuilder.add(ModBlocks.YELLOW_STARTHISTLE,"Yellow Starthistle");
        translationBuilder.add(ModBlocks.YUCCA_FLOWER,"Yucca Flower");


        translationBuilder.add(ModBlocks.JOY_LARGE_LILY,"Joy Large Lily");
        translationBuilder.add(ModBlocks.JOY_LIGHT_LILY,"Joy Light Lily");
        translationBuilder.add(ModBlocks.LAVANDER_LARGE_LILY,"Lavender Large Lily");
        translationBuilder.add(ModBlocks.LAVANDER_LIGHT_LILY,"Lavender Light Lily");
        translationBuilder.add(ModBlocks.PURPLE_LARGE_LILY,"Purple Large Lily");
        translationBuilder.add(ModBlocks.PURPLE_LIGHT_LILY,"Purple Light Lily");
        translationBuilder.add(ModBlocks.SUNFIRE_LARGE_LILY,"Sunfire Large Lily");
        translationBuilder.add(ModBlocks.SUNFIRE_LIGHT_LILY,"Sunfire Light Lily");

        translationBuilder.add(ModBlocks.WISTERIA_LAVANDER,"Wisteria Lavender");
        translationBuilder.add(ModBlocks.WISTERIA_PURPLE,"Wisteria Purple");
        translationBuilder.add(ModBlocks.WISTERIA_WHITE,"Wisteria White");

        translationBuilder.add(ModItems.RACCOON_GRAPE,"Raccoon Grape");
    }
}
